name: Build LÃ–VE package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build .love package
        uses: love-actions/love-actions-core@v1
        with:
          build-list: |
            ./assets/
            ./g3d/
            ./2d.lua
            ./3d.lua
            ./world3d.lua
            ./difficulty.lua
            ./win.lua
            ./main.lua
          package-path: ./build/sudoku.love
